services:
  # Backend API Server
  - type: web
    name: oauth-playground-server
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: oauth-playground-server
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_REDIRECT_URI
        value: https://oauth-playground-client.onrender.com/callback

  # Frontend React App
  - type: static
    name: oauth-playground-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: oauth-playground-server
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html